# Generated by Django 3.2.7 on 2021-09-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersgroups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
