# Generated by Django 3.2.7 on 2021-09-29 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usersgroups', '0002_customgroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
